=== apple/turicreate/deps/src/libxml2-2.9.1/test/schemas/decimal-1.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:simpleType name="myDecimal">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="18"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="foo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="val" type="myDecimal" maxOccurs="unbounded"/>
				<xsd:element name="ref" type="myDecimal" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>

		<!--xsd:key name="myKey">
			<xsd:selector xpath="val"/>
			<xsd:field xpath="."/>
		</xsd:key>

		<xsd:keyref name="myKeyRef" refer="myKey">
			<xsd:selector xpath="ref"/>
			<xsd:field xpath="."/>
		</xsd:keyref-->
	</xsd:element>

</xsd:schema>

=== apple/turicreate/deps/src/libxml2-2.9.1/test/schemas/decimal-1.xml
<?xml version="1.0"?>
<!-- test the values:
	  -  BAD
	  +  BAD
	  1.
	  .1
	  0.
	  .0
	  - 1 BAD
	  + 1 BAD
	  .   BAD
	  000  !
	-->
<foo
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="decimal-1.xsd">
	<!-- The good ones. -->
	<val> 0. </val>
	<val> .0 </val>
	<val> .10 </val>
	<val> 01. </val>
	<val> 000 </val>
	<val>123456789012345678</val>
	<val>-123456789012345678</val>
	<val>0.123456789012345678</val>
	<val>-0.123456789012345678</val>
	<!-- The bad ones. -->
	<val>.</val>
	<val>-</val>
	<val>+</val>
	<val>*</val>
	<val>- 1</val>
	<val>+ 1</val>
	<val>+ 0</val>
	<val>- 0</val>
	<!--ref>0.0</ref-->
</foo>
