=== apple/turicreate/deps/src/libxml2-2.9.1/test/valid/dtds/objednavka.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT objednavka (AdDoručeni, AdÚčtovací, ZpůsobDopravy, ZpůsobPlatby, DatumPřijetí, DatumDoručení, ObsahObjednávky, Komentář?)>
<!ELEMENT  AdDoručeni (Jméno,  Ulice, Město, PSČ)>
<!ELEMENT  AdÚčtovací (Jméno,  Ulice, Město, PSČ)>
<!ELEMENT  Jméno     (#PCDATA)>
<!ELEMENT  Ulice        (#PCDATA)>
<!ELEMENT  Město      (#PCDATA)>
<!ELEMENT  PSČ        (#PCDATA)>
<!ELEMENT ZpůsobDopravy (#PCDATA) >
<!ELEMENT ZpůsobPlatby (#PCDATA) >
<!ELEMENT  DatumPřijetí (#PCDATA)>
<!ELEMENT  DatumDoručení (#PCDATA)>
<!ELEMENT ObsahObjednávky (Zboží+) >
<!ELEMENT Zboží (Kód, Název, Počet, Cena, Popis?) >
<!ELEMENT  Kód (#PCDATA)>
<!ELEMENT Název (#PCDATA) >
<!ELEMENT  Počet (#PCDATA)>
<!ELEMENT Cena (#PCDATA) >
<!ELEMENT Popis (#PCDATA) >
<!ELEMENT Komentář (Řádka*) >
<!ELEMENT  Řádka (#PCDATA)>
<!ATTLIST Počet
                    jednotka      (ks | kg | m2 | m)      #IMPLIED>

=== apple/turicreate/deps/src/libxml2-2.9.1/result/valid/objednavka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE objednavka SYSTEM "dtds/objednavka.dtd">
<objednavka>
    <AdDoručeni>
        <Jméno>Jan Novák</Jméno>
        <Ulice>Bělehradská 147</Ulice>
        <Město>Praha 2</Město>
        <PSČ>12000</PSČ>
    </AdDoručeni>
    <AdÚčtovací>
        <Jméno>Petra Nováková</Jméno>
        <Ulice>Anglická 15</Ulice>
        <Město>Praha 2</Město>
        <PSČ>12000</PSČ>
    </AdÚčtovací>
    <ZpůsobDopravy>DPD</ZpůsobDopravy>
    <ZpůsobPlatby>dobírka</ZpůsobPlatby>
    <DatumPřijetí>2004-11-14</DatumPřijetí>
    <DatumDoručení>2004-11-19</DatumDoručení>
    <ObsahObjednávky>
        <Zboží>
            <Kód>2N7-516</Kód>
            <Název>Sekačka na trávu</Název>
            <Počet jednotka="ks">1</Počet>
            <Cena>2999</Cena>
            <Popis>http://example.org/sekacka.html</Popis>
        </Zboží>
        <Zboží>
            <Kód>Q3Y-116</Kód>
            <Název>Travní semeno</Název>
            <Počet jednotka="kg">2.5</Počet>
            <Cena>127.50</Cena>
        </Zboží>
    </ObsahObjednávky>
    <Komentář>
        <Řádka>O dodávku mám zájem pouze v případě, že se jedná o trávu v odrůdě konopí.</Řádka>
        <Řádka>Dále jsem se chtěl zeptat, zda je doprava zdarma.</Řádka>
    </Komentář>
</objednavka>
